---
title: "test_recruit"
author: "Simon Brunner"
date: "21 December 2017"
output: html_document
---

```{r}
source('../../kaggle_sourcer.R', chdir = T)
```

```{r}
model_dat = tbl_df(fread('output/main_tbl.csv')) %>%
  mutate(target_month=factor(target_month),
         target_year=factor(target_year),
         target_weekday=factor(target_weekday),
         air_genre_name=factor(air_genre_name),
         air_area_name=factor(air_area_name),
         holiday_flg=factor(holiday_flg))
model_dat

target_cols = c('target_day', 'target_month', 'target_weekday', 'target_year', 'air_genre_name', 'air_area_name', 'latitude', 'longitude', 'holiday_flg')
```


```{r}
grid = 10^seq(10, -2, length = 100)
#options(na.action="na.pass")
idx_train = which(model_dat$test==0)
idx_modtrain = sample(x=c(1:length(idx_train)), size = length(idx_train)/2)
x = model.matrix(visitors~., model_dat[,c(target_cols, 'visitors')])
y = model_dat$visitors
y = y/max(y)
lasso_mod = glmnet(x=x[idx_train[idx_modtrain],],
                   y=y[idx_train[idx_modtrain]],alpha = 1)
bestlam = min(lasso_mod$lambda)
plot(lasso_mod)
```

Predictions
```{r}
y_fit = predict(lasso_mod, s=bestlam, newx=x[idx_train[-idx_modtrain],])
plot(y[idx_train[-idx_modtrain]], y_fit)

RMSE = sqrt(mean((y[idx_train[-idx_modtrain]] - y_fit)^2))
RMSE
```

## Try with XGboost
```{r}
library(xgboost)

x = model.matrix(visitors~., model_dat[,c(target_cols, 'visitors')])

#x = sparse.model.matrix(is_churn~.-1, data = tree_dat %>% dplyr::select(-msno, -modtrain, -train, -fee_per_day, -ever_cancelled))
#x = sparse.model.matrix(is_churn~.-1, data = tree_dat %>% dplyr::select(-msno, -modtrain, -train))
y = model_dat$visitors/max(model_dat$visitors)
bst <- xgboost(data = x[idx_train[idx_modtrain], ],
               label = y[idx_train[idx_modtrain]], max_depth = 3, eta = 1, nrounds = 200,
               nthread = 2, objective = "reg:logistic", eval_metric='rmse')
xg_pred = predict(bst, x[idx_train[-idx_modtrain],])
```

```{r}
plt_dat = tbl_df(data.frame(known=y[idx_train[-idx_modtrain]], predicted=xg_pred))

ggplot(plt_dat, aes(x=known, y=predicted)) + geom_point(size=0.2, alpha=0.1)

```

```{r}
RMSE = sqrt(mean((y[idx_train[-idx_modtrain]] - xg_pred)^2))
RMSE
```


### Try clustering locations rather than using coordinates
#### FYI: there are actually just 829 stores...
```{r}
length(unique(model_dat$air_store_id))
```

The stores occur in rather obvious clusters, possibly along a street.
```{r}
ggplot(model_dat, aes(x=latitude, y=longitude)) + geom_point(size=0.2, alpha=0.6)
```

#### Try k-means clustering
...which works pretty well.
```{r}
x_km = as.matrix(model_dat[,c('latitude', 'longitude')])
km = kmeans(x_km, 5, nstart=20)

plt_dat = model_dat
plt_dat$km_assign = km$cluster

ggplot(plt_dat, aes(x=latitude, y=longitude, color=factor(km_assign))) + geom_point(size=0.2, alpha=0.6)
```


